language: elixir
sudo: false
elixir:
  - 1.6
  - 1.5
  - 1.4
otp_release:
  - 20.2
  - 19.3
  - 18.3
matrix:
  exclude:
    - elixir: 1.6
      otp_release: 18.3
notifications:
  email: false
script:
  - mix compile --warnings-as-errors
  - mix credo
  - mix test
